version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - app-network
    environment:
      - HOST=0.0.0.0
      - PORT=8080

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
